"""
Django settings for UserActivity project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hfn8m^ku6b=2j63h^m07x&i&hbar2pyx2@rk1no-er$)#kxbsz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

TIME_ZONE_CHOICES = (
     ('Eniwetok, Kwajalein', '(GMT -12:00) Eniwetok, Kwajalein'),
     ('Midway Island, Samoa', '(GMT -11:00) Midway Island, Samoa'),
     ('Hawaii', '(GMT -10:00) Hawaii'),
     ('Alaska', '(GMT -9:00) Alaska'),
     ('Pacific Time (US &amp; Canada)', '(GMT -8:00) Pacific Time (US &amp; Canada)'),
     ('Mountain Time (US &amp; Canada)', '(GMT -7:00) Mountain Time (US &amp; Canada)'),
     ('-6.0', '(GMT -6:00) Central Time (US &amp; Canada), Mexico City'),
     ('-5.0', '(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima'),
     ('-4.0', '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz'),
     ('-3.5', '(GMT -3:30) Newfoundland'),
     ('-3.0', '(GMT -3:00) Brazil, Buenos Aires, Georgetown'),
     ('-2.0', '(GMT -2:00) Mid-Atlantic'),
     ('-1.0', '(GMT -1:00 hour) Azores, Cape Verde Islands'),
     ('0.0', '(GMT) Western Europe Time, London, Lisbon, Casablanca'),
     ('1.0', '(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris'),
     ('2.0', '(GMT +2:00) Kaliningrad, South Africa'),
     ('3.0', '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg'),
     ('3.5', '(GMT +3:30) Tehran'),
     ('4.0', '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi'),
     ('4.5', '(GMT +4:30) Kabul'),
     ('5.0', '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent'),
     ('5.5', '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi'),
     ('5.75', '(GMT +5:45) Kathmandu'),
     ('6.0', '(GMT +6:00) Almaty, Dhaka, Colombo'),
     ('7.0', '(GMT +7:00) Bangkok, Hanoi, Jakarta'),
     ('8.0', '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong'),
     ('9.0', '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk'),
     ('9.5', '(GMT +9:30) Adelaide, Darwin'),
     ('10.0', '(GMT +10:00) Eastern Australia, Guam, Vladivostok'),
     ('11.0', '(GMT +11:00) Magadan, Solomon Islands, New Caledonia'),
     ('12.0', '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka')
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userapp',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UserActivity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UserActivity.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
